export const FETCH_USER = 'FETCH_USER'
export const UPDATE_USERS = 'UPDATE_USERS'

export const SHOW_ELEMENTS = 'SHOW_ELEMENTS'

export const POST_TICKET = 'POST_TICKET'
export const FETCH_TICKETS = 'FETCH_TICKETS'
export const UPDATE_TICKETS = 'UPDATE_TICKETS'
export const UPDATE_CURRENT_TICKET = 'UPDATE_CURRENT_TICKET'

